#!/bin/bash

if [[ `id -u` -ne 0 ]]; then
	echo "Run it as root ... ";
	exit 1
fi

printf "############### \x1b[33mExtender v(0.1.0)\x1b[0m ############### \n"

# check for hostapd
printf "~> checking for hostapd ... ";
if [[ -e /usr/sbin/hostapd ]]; then
	printf "ok\n"
	sleep 0.5
	printf "\033[A\33[2K\r"
else
	echo "not found";
	printf "Installing ... hostapd \n"
	sudo apt-get install hostapd;
	if [[ $? -ne 0 ]]; then
		echo "Failed"
		exit 1
	fi
fi
# Check for dnsmasq
printf "~> checking for dnsmasq ... ";
if [[ -e /usr/sbin/dnsmasq ]]; then
	printf "ok\n"
	sleep 0.5
	printf "\033[A\33[2K\r"
	
else
	echo "not found"
	printf "Installing ... dnsmasq \n"
	sudo apt-get install dnsmasq;
	if [[ $? -ne 0 ]]; then
		echo "Failed"
		exit 1
	fi
fi

# this is the default ip assigned to interface 

# you can change it but you also need to update dnsmasq.conf file so i
# recommend not to change it
sudo ifconfig wlan0 down
sudo ifconfig wlan0 192.168.28.1 up

echo "~> IP address for wlan0 Interface is 192.168.28.1"

if [[ -e /etc/hotspot.conf ]]; then
	echo "~> hotspot.conf exists ..."
else
	printf "~> creating hotspot.conf file ... "
	sudo touch /etc/hotspot.conf
	sleep 0.1
	echo "ssid=WlanActivation" > "/etc/hotspot.conf"
	echo "pw=12345678" > "/etc/hotspot.conf"
	echo "ok"
fi

while read p; do
	if [[ $p == *=* ]]; then
		IFS='=' read -r -a array <<< $p
		if [[ $array[0] == "ssid" ]]; then
			ntname="${$array[1]}"
		fi
		if [[ $array[0] == "pw"]]
			ntpass="${$array[1]}"
		fi
	fi
done < /etc/hotspot.conf

if [[ -z $ntname ]]; then
	exit 1
fi

if [[ -z $ntpass ]]; then
	exit 1
fi

sudo systemctl stop dnsmasq

##############################################
if [[ -e /etc/dnsmasq.conf ]]; then
	echo "~> dnsmasq.conf exists ... "
	sleep 0.1
	printf "\033[A\33[2K\r~> updating dnsmasq.conf file ... ";
	#######################################################
	echo "interface=wlan0" > /etc/dnsmasq.conf
	echo "no-resolv" >> /etc/dnsmasq.conf
	echo "expand-hosts" >> /etc/dnsmasq.conf
    echo "dhcp-authoritative" >> /etc/dnsmasq.conf
	echo "dhcp-range=192.168.28.2,192.168.28.254,255.255.255.0,24h" >> /etc/dnsmasq.conf
	echo "dhcp-range=127.0.0.2,127.0.0.25,24h" >> /etc/dnsmasq.conf
	echo "dhcp-option=3,192.168.28.1" >> /etc/dnsmasq.conf
	echo "dhcp-option=6,192.168.28.1" >> /etc/dnsmasq.conf
	echo "dhcp-option=1,255.255.255.0" >> /etc/dnsmasq.conf
	echo "server=8.8.8.8" >> /etc/dnsmasq.conf
	echo "server=8.8.4.4" >> /etc/dnsmasq.conf
	echo "log-queries" >> /etc/dnsmasq.conf
	echo "log-dhcp" >> /etc/dnsmasq.conf
	echo "listen-address=192.168.28.1,127.0.0.1,::" >> /etc/dnsmasq.conf
	echo "ok"
	##########################################################
else
	printf "~> creating dnsmasq.conf file ... "
	sudo touch /etc/dnsmasq.conf
	echo "ok"
	sleep 0.1
	printf "\033[A\33[2K\r~> updating dnsmasq.conf file ... ";
	#########################################################
	echo "interface=wlan0" > /etc/dnsmasq.conf
	echo "no-resolv" >> /etc/dnsmasq.conf
	echo "expand-hosts" >> /etc/dnsmasq.conf
	echo "dhcp-authoritative" >> /etc/dnsmasq.conf
	echo "dhcp-range=192.168.28.2,192.168.28.254,255.255.255.0,24h" >> dnsmasq.conf
	echo "dhcp-range=127.0.0.2,127.0.0.25,24h" >> /etc/dnsmasq.conf
	echo "dhcp-option=3,192.168.28.1" >> /etc/dnsmasq.conf
	echo "dhcp-option=6,192.168.28.1" >> /etc/dnsmasq.conf
	echo "dhcp-option=1,255.255.255.0" >> /etc/dnsmasq.conf
	echo "server=8.8.8.8" >> /etc/dnsmasq.conf
	echo "server=8.8.4.4" >> /etc/dnsmasq.conf
	echo "log-queries" >> /etc/dnsmasq.conf
	echo "log-dhcp" >> /etc/dnsmasq.conf
	echo "listen-address=192.168.28.1,127.0.0.1,::" >> /etc/dnsmasq.conf
	##########################################################
	echo "ok"
fi

####################################################
if [[ -e /etc/hostapd.conf ]]; then
	echo "~> hostapd.conf exists ... "
	sleep 0.1
	printf "\033[A\33[2K\r~> updating hostapd.conf file ... "
	############################################
	echo "interface=wlan0" > /etc/hostapd.conf
	echo "driver=nl80211" >> /etc/hostapd.conf 
	echo "ssid=$ntname" >> /etc/hostapd.conf 
	echo "channel=$((RANDOM%11 + 1))" >> /etc/hostapd.conf 
	echo "hw_mode=g" >> /etc/hostapd.conf 
	echo "wme_enabled=1" >> /etc/hostapd.conf 
	echo "macaddr_acl=0" >> /etc/hostapd.conf 
	echo "auth_algs=1" >> /etc/hostapd.conf 
	echo "ignore_broadcast_ssid=0" >> /etc/hostapd.conf 
	echo "wpa=2" >> /etc/hostapd.conf 
	echo "wpa_passphrase=$ntpass" >> /etc/hostapd.conf 
	echo "wpa_key_mgmt=WPA-PSK" >> /etc/hostapd.conf 
	echo "wpa_pairwise=TKIP" >> /etc/hostapd.conf 
	echo "rsn_pairwise=CCMP" >> /etc/hostapd.conf 
	echo "ok"
	##############################################
else
	printf "~> creating hostapd.conf file ... "
	sudo touch /etc/hostapd.conf
	echo "ok"
	sleep 0.1
	#############################################
	printf "\033[A\33[2K\r~> updating hostapd.conf file ... "
	echo "interface=wlan0" > /etc/hostapd.conf
	echo "driver=nl80211" >> /etc/hostapd.conf 
	echo "ssid=$ntname" >> /etc/hostapd.conf 
	echo "channel=$((RANDOM%11 + 1))" >> /etc/hostapd.conf 
	echo "hw_mode=g" >> /etc/hostapd.conf 
	echo "wme_enabled=1" >> /etc/hostapd.conf 
	echo "macaddr_acl=0" >> /etc/hostapd.conf 
	echo "auth_algs=1" >> /etc/hostapd.conf 
	echo "ignore_broadcast_ssid=0" >> /etc/hostapd.conf 
	echo "wpa=2" >> /etc/hostapd.conf 
	echo "wpa_passphrase=$ntpass" >> /etc/hostapd.conf 
	echo "wpa_key_mgmt=WPA-PSK" >> /etc/hostapd.conf 
	echo "wpa_pairwise=TKIP" >> /etc/hostapd.conf 
	echo "rsn_pairwise=CCMP" >> /etc/hostapd.conf 
	##############################################
	echo "ok"
fi

echo "Extender Service Started ... "

sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state ESTABLISHED,RELATED -j ACCEPT
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo echo 1 > /proc/sys/net/ipv4/ip_forward

sudo systemctl start dnsmasq
sudo sudo hostapd /etc/hostapd.conf

sudo systemctl stop dnsmasq

echo "###############    Bye    ###############";
exit 0
